"""init

Revision ID: ef2a10eeaf65
Revises: 
Create Date: 2019-05-10 18:10:39.367643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2a10eeaf65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dancer',
    sa.Column('dancer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('dancer_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discipline',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('discipline_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('start_page', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_access'), 'user', ['access'], unique=False)
    op.create_table('couple',
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('follow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follow_id'], ['dancer.dancer_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['dancer.dancer_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('couple_id'),
    sa.UniqueConstraint('lead_id', 'follow_id', name='_lead_follow_uc')
    )
    op.create_table('dance',
    sa.Column('dance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=6), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.discipline_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dance_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('heat',
    sa.Column('heat_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.discipline_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['level.level_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('heat_id')
    )
    op.create_table('grading_heat',
    sa.Column('grading_heat_id', sa.Integer(), nullable=False),
    sa.Column('heat_id', sa.Integer(), nullable=True),
    sa.Column('dance_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dance_id'], ['dance.dance_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['heat_id'], ['heat.heat_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grading_heat_id')
    )
    op.create_table('heat_couple',
    sa.Column('heat_id', sa.Integer(), nullable=True),
    sa.Column('couple_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couple.couple_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['heat_id'], ['heat.heat_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.UniqueConstraint('heat_id', 'couple_id', name='_heat_couple_uc')
    )
    op.create_table('grade',
    sa.Column('grading_id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=True),
    sa.Column('grading_heat_id', sa.Integer(), nullable=True),
    sa.Column('lead_diploma', sa.Boolean(), nullable=False),
    sa.Column('lead_grade', sa.Integer(), nullable=False),
    sa.Column('follow_diploma', sa.Boolean(), nullable=False),
    sa.Column('follow_grade', sa.Integer(), nullable=False),
    sa.Column('adjudicator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['couple_id'], ['couple.couple_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grading_heat_id'], ['grading_heat.grading_heat_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grading_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    op.drop_table('heat_couple')
    op.drop_table('grading_heat')
    op.drop_table('heat')
    op.drop_table('dance')
    op.drop_table('couple')
    op.drop_index(op.f('ix_user_access'), table_name='user')
    op.drop_table('user')
    op.drop_table('level')
    op.drop_table('discipline')
    op.drop_table('dancer')
    # ### end Alembic commands ###
